### ISSUE TITLE
Installation problem for R devel (4.1) on Windows

### ISSUE THREAD

**Issue by ravolio** [lawremi/rtracklayer#44]
Hi,

I am having problems trying to install rtracklayer devel version on Windows.
From what I have seen, this is a general problem related to the Windows OS, right? Do you expect to fix the problem anytime soon?

Thank you,
Rosario

**Comment by hpages** [comment]
[This line](https://github.com/lawremi/rtracklayer/blob/d5321c719b9a803597eca51bf854017181f4bea2/src/ucsc/udc.c#L46) (introduced at commit d5321c719b9a803597eca51bf854017181f4bea2) breaks the package on Windows:

https://bioconductor.org/checkResults/3.13/bioc-LATEST/rtracklayer/riesling1-install.html

We didn't see a catastrophic chain reaction (hundreds of packages depend directly or indirectly on rtracklayer) on the Windows builds so far because the last working version of the package was automatically restored after each failed installation of the latest version. However, we updated R on the devel builders yesterday so now rtracklayer is no longer on the Windows builder. This means that you can expect a lot of red today or maybe tomorrow on the build report for the Windows results.

**Comment by sanchit-saini** [comment]
Thanks @hpages for looking into the issue.
I'm working on it and will try to fix it ASAP.
