### ISSUE TITLE
`restfulr::download.file` usage results in warning

### ISSUE THREAD

**Issue by mjsteinbaugh** [lawremi/rtracklayer#71]
Hi @lawremi ,

I noticed with rtracklayer 1.56.0 on R 4.2 / Bioconductor 3.15 that loading rtracklayer now results in this warning:

```r
replacing previous import 'utils::download.file' by 'restfulr::download.file'
```

Would it be possible to rename this conflict in restfulr?

Best,
Mike

**Comment by mjsteinbaugh** [comment]
Issue https://github.com/lawremi/rtracklayer/issues/69 is also somewhat related

**Comment by mjsteinbaugh** [comment]
PS thanks again for rtracklayer, it's awesome

**Comment by almeidasilvaf** [comment]
Hi, @lawremi 

I have the same problems reported in this issue and in #69 when trying to pass URLs to import(). I think the problem is indeed because you pushed a broken version of `restfulr` to CRAN. It was working fine for me yesterday in the morning, but then I had to upgrade `GenomicRanges` and all its dependencies were upgraded, including rtracklayer and restfulr. After the upgrade, import() does not work with URLs anymore.

I tried to install the previous version of restfulr from GitHub, but I could not find the repo. Is restfulr not in a GitHub repo?

For those who are reading this issue and, like me, need an urgent solution for this bug, here is a workaround:

```{r}
# Example GFF3 file
url <- "ftp://ftp.psb.ugent.be/pub/plaza/plaza_pico_03/GFF/ppa/annotation.selected_transcript.exon_features.ppa.gff3.gz"

# Download GFF3 file to tempdir
dfile <- file.path(tempdir(), basename(x))
utils::download.file(x, dfile) # download GFF3 file to

# Read GFF3 file as GRanges object
ranges <- rtracklayer::import(dfile)

# Leave no traces
unlink(dfile)
```

**Comment by lawremi** [comment]
restfulr 0.15 is on its way to CRAN.

**Comment by lawremi** [comment]
I think this should be resolved now? Please reopen if not.

**Comment by mjsteinbaugh** [comment]
Looks to be fixed, thanks!
